version: '3.8'

services:
    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        ports:
            - "5432:5432"
        restart: on-failure

    pgweb:
        image: sosedoff/pgweb
        depends_on:
            - postgres
        environment:
            PGWEB_DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}?sslmode=disable
        ports:
            - "8081:8081"
        restart: on-failure


    redis:
        image: redis:latest
        command: redis-server
        volumes:
            - redis:/var/lib/redis
            - redis-config:/usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        networks:
            - redis-network
        restart: on-failure

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
            - HTTP_USER=${REDIS_USER}
            - HTTP_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "8082:8081"
        networks:
            - redis-network
        depends_on:
            - redis
        restart: on-failure

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: on-failure

volumes:
    redis:
    redis-config:

networks:
    redis-network:
        driver: bridge
