/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "stancl.tenancy.asset": [
        {
            "name": "path",
            "required": false
        }
    ],
    "landing-page": [],
    "about": [],
    "pricing": [],
    "dashboard": [],
    "organisations.applications.create.step": [
        {
            "name": "application",
            "required": true
        },
        {
            "name": "step",
            "required": true
        }
    ],
    "organisations.applications.store.step": [
        {
            "name": "application",
            "required": true
        },
        {
            "name": "step",
            "required": true
        }
    ],
    "organisations.applications.restore": [
        {
            "name": "application",
            "required": true
        }
    ],
    "organisations.applications.submit": [
        {
            "name": "application",
            "required": true
        }
    ],
    "organisations.applications.index": [],
    "organisations.applications.create": [],
    "organisations.applications.store": [],
    "organisations.applications.show": [
        {
            "name": "application",
            "required": true
        }
    ],
    "organisations.applications.edit": [
        {
            "name": "application",
            "required": true
        }
    ],
    "organisations.applications.update": [
        {
            "name": "application",
            "required": true
        }
    ],
    "organisations.applications.destroy": [
        {
            "name": "application",
            "required": true
        }
    ],
    "tenant.landing-page": [],
    "tenant.dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "language": [
        {
            "name": "language",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
