/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'sanctum.csrf-cookie': []
        'stancl.tenancy.asset': [
            {
                name: 'path'
                required: false
            },
        ]
        'landing-page': []
        about: []
        pricing: []
        dashboard: []
        'settings.profile.edit': []
        'settings.profile.update': []
        'settings.profile.destroy': []
        'settings.applications.create.step': [
            {
                name: 'application'
                required: true
            },
            {
                name: 'step'
                required: true
            },
        ]
        'settings.applications.store.step': [
            {
                name: 'application'
                required: true
            },
            {
                name: 'step'
                required: true
            },
        ]
        'settings.applications.restore': [
            {
                name: 'application'
                required: true
            },
        ]
        'settings.applications.submit': [
            {
                name: 'application'
                required: true
            },
        ]
        'settings.applications.index': []
        'settings.applications.create': []
        'settings.applications.store': []
        'settings.applications.show': [
            {
                name: 'application'
                required: true
            },
        ]
        'settings.applications.edit': [
            {
                name: 'application'
                required: true
            },
        ]
        'settings.applications.update': [
            {
                name: 'application'
                required: true
            },
        ]
        'settings.applications.destroy': [
            {
                name: 'application'
                required: true
            },
        ]
        'tenant.landing-page': []
        'organisation.invitations.accept': [
            {
                name: 'token'
                required: true
            },
        ]
        'tenant.dashboard': []
        'settings.invitations.resend': [
            {
                name: 'id'
                required: true
            },
        ]
        'settings.invitations.index': []
        'settings.invitations.create': []
        'settings.invitations.store': []
        'settings.invitations.show': [
            {
                name: 'invitation'
                required: true
            },
        ]
        'settings.members.index': []
        'animals.dogs.publish': [
            {
                name: 'id'
                required: true
            },
        ]
        'animals.dogs.index': []
        'animals.dogs.create': []
        'animals.dogs.store': []
        'animals.dogs.show': [
            {
                name: 'animal'
                required: true
            },
        ]
        'animals.dogs.edit': [
            {
                name: 'animal'
                required: true
            },
        ]
        'animals.dogs.update': [
            {
                name: 'animal'
                required: true
            },
        ]
        'animals.dogs.destroy': [
            {
                name: 'animal'
                required: true
            },
        ]
        'animals.cats.publish': [
            {
                name: 'id'
                required: true
            },
        ]
        'animals.cats.index': []
        'animals.cats.create': []
        'animals.cats.store': []
        'animals.cats.show': [
            {
                name: 'animal'
                required: true
            },
        ]
        'animals.cats.edit': [
            {
                name: 'animal'
                required: true
            },
        ]
        'animals.cats.update': [
            {
                name: 'animal'
                required: true
            },
        ]
        'animals.cats.destroy': [
            {
                name: 'animal'
                required: true
            },
        ]
        'animals.browse': []
        'animals.show': [
            {
                name: 'id'
                required: true
            },
        ]
        language: [
            {
                name: 'language'
                required: true
            },
        ]
        register: []
        login: []
        'password.request': []
        'password.email': []
        'password.reset': [
            {
                name: 'token'
                required: true
            },
        ]
        'password.store': []
        'verification.notice': []
        'verification.verify': [
            {
                name: 'id'
                required: true
            },
            {
                name: 'hash'
                required: true
            },
        ]
        'verification.send': []
        'password.confirm': []
        'password.update': []
        logout: []
        'storage.local': [
            {
                name: 'path'
                required: true
            },
        ]
    }
}
export {}
