name: Prettier Check

on: [pull_request]

permissions:
  pull-requests: write
  contents: read
  packages: read

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run check-format

      - name: Annotate Pull Request with Results
        uses: actions/github-script@v7
        if: failure()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Prettier found formatting issues. Please run `npm run format` to fix them.'
            })
